/**
 * Sí el layout por alguna razon se elimina
 * Next.js lo crea automaticamente
 */
import Footer from "@/components/Footer"
import Header from "@/components/Header"

import { Metadata } from 'next'


export const metadata: Metadata = {
  title: {
    default: "Next.js example - Title default", // Si una ruta por ejemplo /blog no tiene Metadata, se mostrara esta...
    template: "%s | add this example", // Por ejemplo en /docs si tiene un titulo en los metadatas por ejemplo Docs... se mostrar: Docs... | add this example
    absolute: ""
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
