/**
 * Sí el layout por alguna razon se elimina
 * Next.js lo crea automaticamente
 */
import Footer from "@/components/Footer"
import Header from "@/components/Header"


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
